## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {

}


## Write a short comment describing this function

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
}
makeCacheMatrix <- function(x) {
# Dear classmate,
# Thanks for checking my programming assignment.
# Apparently, everything I changed was just a few lines in the sample code we
# got as an example. So, I just provide this code with some comments.

# So, m is the inverse matrix. Here, when we pass a new matrix to the 
# makeCacheMatrix, this value is set to NULL which indicates that there is no
# inverse matrix calculated yet.
        m <- NULL

# This function sets m and x in the parent environment using lexical scoping.
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
# Get returns the value of the matrix
        get <- function() x
# Setinv inverses the matrix
        setinv <- function(solve) m <<- solve
# Getinv returns the inverse value or whatever is written in it (maybe NULL)
        getinv <- function() m

#Returning the list
        list(set = set, get = get,
             setinv = setinv,
             getinv = getinv)
}

# This function solves the matrix and writes the value in the cache
cacheSolve <- function(x, ...) { #x is the generated by the makeCacheMatrix
        m <- x$getinv() # Read the cached value which is either NULL if the 
# matrix is 'fresh' or an inverse matrix of x
        if(!is.null(m)) { # So if m isn't NULL the inverse is already 
# calculated and the value is returned
                message("getting cached data")
                return(m)
        }
        data <- x$get() # Using get function the matrix for inversion is read
        m <- solve(data, ...) # So, here the matrix is actually inversed 
        x$setinv(m) # The inversed value is saved to the input variable
        m 
# Returned value
}
